export enum TypeTest {
  CONSTANT_LOAD_TEST="CONSTANT_LOAD_TEST",
  RAMP_LOAD_TEST="RAMP_LOAD_TEST",
  SPIKE_LOAD_TEST="SPIKE_LOAD_TEST",
  STRESS_LOAD_TEST="STRESS_LOAD_TEST",
  Exponential_Load_Test="Exponential_Load_Test",
  IP_SPOOFING="IP_SPOOFING",
  CAPACITY_TEST="CAPACITY_TEST",
  SOAK_LOAD_TEST="SOAK_LOAD_TEST",
  BURST_TEST="BURST_TEST",
  Step_Load_Model="Step_Load_Model",
  CUSTOMIZED="CUSTOMIZED",
  }
