export enum TypeTest {
  LOGARITHMIC_LOAD_MODEL='LOGARITHMIC_LOAD_MODEL',
  EXPONENTIEL_LOAD_MODEL='EXPONENTIEL_LOAD_MODEL',
  SPIKE_LOAD_TEST='SPIKE_LOAD_TEST',
  STRESS_LOAD_TEST='STRESS_LOAD_TEST',
  CONSTANT_LOAD_MODEL='CONSTANT_LOAD_MODEL',
  SOAK_MODEL='SOAK_MODEL',
  CAPACITY_TEST='CAPACITY_TEST',
  }
